"""Add contact and address to proyecto

Revision ID: 1ac7fc54f1ae
Revises: 858cb3bd6a96
Create Date: 2026-03-06 11:57:13.909419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac7fc54f1ae'
down_revision: Union[str, None] = '858cb3bd6a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos', sa.Column('telefono_contacto', sa.String(), nullable=True))
    op.add_column('proyectos', sa.Column('correo_contacto', sa.String(), nullable=True))
    op.add_column('proyectos', sa.Column('direccion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proyectos', 'direccion')
    op.drop_column('proyectos', 'correo_contacto')
    op.drop_column('proyectos', 'telefono_contacto')
    # ### end Alembic commands ###
