"""Rename comprador to cliente and add fields

Revision ID: 911f609afac5
Revises: b6553511e522
Create Date: 2026-03-12 01:09:55.342450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '911f609afac5'
down_revision: Union[str, None] = 'b6553511e522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('documento_identidad', sa.String(), nullable=True),
    sa.Column('entidad_financiera', sa.String(), nullable=True),
    sa.Column('estado_credito', postgresql.ENUM('preaprobado', 'aprobado', 'definitivo', name='estadocredito', create_type=False), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=True)
    
    op.add_column('apartamentos', sa.Column('cliente_id', sa.UUID(), nullable=True))
    op.drop_constraint('apartamentos_comprador_id_fkey', 'apartamentos', type_='foreignkey')
    op.create_foreign_key(None, 'apartamentos', 'clientes', ['cliente_id'], ['id'])
    op.drop_column('apartamentos', 'comprador_id')
    
    op.drop_index('ix_compradores_email', table_name='compradores')
    op.drop_table('compradores')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartamentos', sa.Column('comprador_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'apartamentos', type_='foreignkey')
    op.create_foreign_key('apartamentos_comprador_id_fkey', 'apartamentos', 'compradores', ['comprador_id'], ['id'])
    op.drop_column('apartamentos', 'cliente_id')
    op.create_table('compradores',
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entidad_financiera', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estado_credito', postgresql.ENUM('preaprobado', 'aprobado', 'definitivo', name='estadocredito'), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='compradores_pkey')
    )
    op.create_index('ix_compradores_email', 'compradores', ['email'], unique=True)
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
