"""Add Cargo and Modality to Empleados

Revision ID: b6553511e522
Revises: 5d894b8c00e1
Create Date: 2026-03-08 22:03:29.565970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6553511e522'
down_revision: Union[str, None] = '5d894b8c00e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    modalidad_enum = sa.Enum('presencial', 'remoto', 'hibrido', name='modalidadtrabajo')
    modalidad_enum.create(bind, checkfirst=True)

    op.create_table('cargos',
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.add_column('empleados', sa.Column('cargo_id', sa.UUID(), nullable=True))
    op.add_column('empleados', sa.Column('modalidad', sa.Enum('presencial', 'remoto', 'hibrido', name='modalidadtrabajo', create_type=False), nullable=True))
    op.add_column('empleados', sa.Column('rol', sa.Enum('super_admin', 'admin', 'asesor', name='rolusuario', create_type=False), nullable=True))
    op.create_foreign_key(None, 'empleados', 'cargos', ['cargo_id'], ['id'])
    op.drop_column('empleados', 'cargo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('cargo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'empleados', type_='foreignkey')
    op.drop_column('empleados', 'rol')
    op.drop_column('empleados', 'modalidad')
    op.drop_column('empleados', 'cargo_id')
    op.drop_table('cargos')
    # ### end Alembic commands ###
